name: easyridev2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: any
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.0
  osrm: ^0.0.8
  cupertino_icons:
  url_launcher: ^6.2.5
  geocoding: ^2.1.1
  http: ^1.1.0
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  image_picker: ^1.0.7
  file_picker: ^10.2.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - black bg for easy ride-02.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "black bg for easy ride-02.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "black bg for easy ride-02.jpg"

flutter_native_splash:
  color: "#000000"
  image: "black bg for easy ride-02.jpg"
  android: true
  ios: true
  web: false
